//! 生成前端 TS 文本：`listens.ts`（事件名常量）与 `bindings.ts`（类型 + 命令包装）

use std::collections::BTreeMap;

use crate::{
    Decl, Sig,
    scan::{rename_all_of, split_top_level},
    ts::{camel, pascal, ts_field},
};

/// `mml-vue/src/lib/listens.ts`
pub(crate) fn listens_ts(events: &[String]) -> String {
    let mut ts = String::from(
        "// @generated by mml-gui/src-tauri/build.rs —— 勿手改，新增事件请给函数加 gui_macros::emit 标记\n\n",
    );
    for name in events {
        ts.push_str(&format!(
            "export const {}: string = \"{}\"\n",
            pascal(name),
            name
        ));
    }
    ts
}

/// `mml-vue/src/lib/bindings.ts`
pub(crate) fn bindings_ts(decls: &[Decl], sigs: &[Sig], ext: &BTreeMap<String, String>) -> String {
    let mut b = String::from(
        "// @generated by mml-gui/src-tauri/build.rs —— 勿手改\n\
         //\n\
         // 命令的类型化包装 + 跨 IPC 类型的 TS 定义，都由 Rust 侧源码扫描生成。\n\n\
         import { invoke } from \"@tauri-apps/api/core\";\n\n",
    );

    append_commands(&mut b, sigs);
    append_types(&mut b, decls, ext);

    b
}

/// 命令表：按来源 .rs 模块分组（AGENTS §4 下，命令名 = 窗口名_方法名，
/// 所以同一文件里的命令共享同一个前段；把它剥掉，组内只剩方法名）
fn append_commands(b: &mut String, sigs: &[Sig]) {
    b.push_str("/** 命令，按来源 .rs 模块分组（参数顺序与 Rust 一致，Tauri 注入的 AppHandle/WebviewWindow 已剔除）*/\n");
    b.push_str("export const commands = {\n");

    // 归组：组键 = 显式分组标记（`#[ipc_group("...")]`）或来源模块最后一段。
    //
    // 输出顺序**沿用"组键首次出现"的顺序**，不按组键排序：不设显式分组时组键与来源模块
    // 一一对应，输出与旧版逐字节一致；设了分组的子模块并进它所属的组，位置取首次出现处。
    let mut order: Vec<String> = Vec::new();
    let mut grouped: BTreeMap<String, Vec<&Sig>> = BTreeMap::new();
    for s in sigs {
        let key = s.group_key().to_string();
        if !grouped.contains_key(&key) {
            order.push(key.clone());
        }
        grouped.entry(key).or_default().push(s);
    }

    for key in order {
        let group = &grouped[&key];
        let group_key = camel(&key);

        // 组内命令名的公共前段，按 `_` 分段取最长公共前缀
        // （`add.rs` -> `add`；`add_modpack.rs` -> `add_modpack`；`window_manager.rs` -> `window`）
        let segs = |n: &str| n.split('_').map(|s| s.to_string()).collect::<Vec<_>>();
        let mut common = segs(&group[0].name);
        for s in group {
            let other = segs(&s.name);
            let mut k = 0;
            while k < common.len() && k < other.len() && common[k] == other[k] {
                k += 1;
            }
            common.truncate(k);
        }
        // 公共前缀不能吃掉整个名字，否则方法名会空（单命令组会走到这里）
        let mut strip_len = common.len();
        if strip_len > 0 && group.iter().any(|s| segs(&s.name).len() == strip_len) {
            strip_len -= 1;
        }
        let strip = if strip_len == 0 {
            None
        } else {
            Some(common[..strip_len].join("_") + "_")
        };

        b.push_str(&format!("  {group_key}: {{\n"));

        // 组内按**最终方法名**排序：命令在文件之间怎么搬都不影响生成结果
        // （拆文件时 bindings.ts 逐字节不变，正是"这次拆分安全"的判据）
        let mut entries: Vec<(String, &Sig)> = group
            .iter()
            .map(|s| {
                let method = camel(match &strip {
                    Some(prefix) => s.name.strip_prefix(prefix).unwrap_or(&s.name),
                    None => s.name.as_str(),
                });
                (method, *s)
            })
            .collect();
        entries.sort_by(|a, b| a.0.cmp(&b.0));

        for (method, s) in entries {
            let name = &s.name;
            let ret = &s.ret;
            let list = s
                .params
                .iter()
                .map(|(n, t, opt)| format!("{n}{}: {t}", if *opt { "?" } else { "" }))
                .collect::<Vec<_>>()
                .join(", ");
            let arg = if s.params.is_empty() {
                String::new()
            } else {
                let obj = s
                    .params
                    .iter()
                    .map(|(n, _, _)| n.clone())
                    .collect::<Vec<_>>()
                    .join(", ");
                format!(", {{ {obj} }}")
            };
            b.push_str(&format!(
                "    {method}: ({list}) => invoke<{ret}>(\"{name}\"{arg}),\n"
            ));
        }
        b.push_str("  },\n");
    }
    b.push_str("};\n\n");
}

/// 类型定义：枚举生成字符串联合，struct 逐字段转 TS（rename_all 生效）
fn append_types(b: &mut String, decls: &[Decl], ext: &BTreeMap<String, String>) {
    b.push_str("/** 类型 */\n");
    for d in decls {
        let rename_all = rename_all_of(&d.attrs);
        if d.is_enum {
            let variants: Vec<String> = split_top_level(&d.body)
                .into_iter()
                .filter_map(|v| {
                    // 跳过变体前置的文档注释与属性（如 `#[default]`），再取标识符
                    let line = v
                        .lines()
                        .map(|l| l.trim())
                        .find(|l| !l.is_empty() && !l.starts_with("//") && !l.starts_with("#["))?;
                    let name: String = line
                        .chars()
                        .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
                        .collect();
                    if name.is_empty() {
                        return None;
                    }
                    Some(match rename_all.as_deref() {
                        Some("lowercase") => name.to_ascii_lowercase(),
                        Some("camelCase") => camel(&name),
                        _ => name,
                    })
                })
                .collect();
            b.push_str(&format!(
                "export type {} = {};\n\n",
                d.name,
                variants
                    .iter()
                    .map(|v| format!("\"{v}\""))
                    .collect::<Vec<_>>()
                    .join(" | ")
            ));
            continue;
        }

        // 只 derive Deserialize = 前端传给后端的入参 DTO（字段可缺省，见 ts_field）
        let input_only = !d.attrs.contains("Serialize");
        b.push_str(&format!("export type {} = {{\n", d.name));
        for line in d.body.lines() {
            let line = line.trim();
            if line.starts_with("//") || line.starts_with("#[") || line.is_empty() {
                continue;
            }
            let Some((raw_name, raw_ty)) = line.split_once(':') else {
                continue;
            };
            let raw_name = raw_name.trim().trim_start_matches("pub ").trim();
            if raw_name.is_empty() || raw_name.starts_with('/') {
                continue;
            }
            let raw_name = raw_name.trim_start_matches("r#");
            let raw_ty = raw_ty.trim().trim_end_matches(',').trim();
            let ts_name = match rename_all.as_deref() {
                Some("camelCase") => camel(raw_name),
                Some("lowercase") => raw_name.to_ascii_lowercase(),
                _ => raw_name.to_string(),
            };
            let (ts, opt) = ts_field(raw_ty, input_only, ext);
            b.push_str(&format!(
                "  {ts_name}{}: {ts},\n",
                if opt { "?" } else { "" }
            ));
        }
        b.push_str("};\n\n");
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{Decl, Sig};

    fn sig(module: &str, name: &str, params: Vec<(&str, &str, bool)>, ret: &str) -> Sig {
        Sig {
            module: module.into(),
            name: name.into(),
            group: None,
            params: params
                .into_iter()
                .map(|(n, t, o)| (n.into(), t.into(), o))
                .collect(),
            ret: ret.into(),
        }
    }

    /// 带显式分组的签名（模拟拆到子模块里的命令）
    fn sig_group(module: &str, name: &str, group: &str) -> Sig {
        Sig {
            group: Some(group.into()),
            ..sig(module, name, vec![], "void")
        }
    }

    fn decl(name: &str, attrs: &str, body: &str, is_enum: bool) -> Decl {
        Decl {
            name: name.into(),
            attrs: attrs.into(),
            body: body.into(),
            is_enum,
        }
    }

    /// 组键取模块最后一段，方法名剥掉组内公共前段
    #[test]
    fn test_group_and_prefix_strip() {
        let sigs = vec![
            sig(
                "windows::add_modpack",
                "add_modpack_search",
                vec![("source", "string", false)],
                "ModpackSearchDto",
            ),
            sig("windows::add_modpack", "add_modpack_start", vec![], "void"),
        ];
        let out = bindings_ts(&[], &sigs, &BTreeMap::new());
        assert!(out.contains("  addModpack: {\n"), "{out}");
        assert!(out.contains("    search: (source: string) => invoke<ModpackSearchDto>(\"add_modpack_search\", { source }),\n"), "{out}");
        // 无参数的命令不带对象实参
        assert!(
            out.contains("    start: () => invoke<void>(\"add_modpack_start\"),\n"),
            "{out}"
        );
    }

    /// 显式分组：子模块的命令并回原来的组，组键与组内公共前段剥离都不受影响
    #[test]
    fn test_explicit_group_merges_submodule() {
        // 与 lib.rs 的排序一致：按 (module, name)
        let sigs = vec![
            sig("windows::resource", "resource_list_saves", vec![], "void"),
            sig_group(
                "windows::resource::screenshots",
                "resource_delete_screenshot",
                "resource",
            ),
            sig_group(
                "windows::resource::screenshots",
                "resource_list_screenshots",
                "resource",
            ),
        ];
        let out = bindings_ts(&[], &sigs, &BTreeMap::new());
        assert_eq!(out.matches("  resource: {\n").count(), 1, "{out}");
        assert!(
            out.contains(
                "    listScreenshots: () => invoke<void>(\"resource_list_screenshots\"),\n"
            ),
            "{out}"
        );
        assert!(
            out.contains(
                "    deleteScreenshot: () => invoke<void>(\"resource_delete_screenshot\"),\n"
            ),
            "{out}"
        );
        // 组内顺序按最终方法名（与命令放在哪个文件无关）：
        // clear/delete/list 的字典序 —— 这正是"拆文件不改生成结果"的保证
        let body = out.split("  resource: {").nth(1).unwrap();
        let order: Vec<&str> = [
            "clearScreenshots",
            "deleteScreenshot",
            "listSaves",
            "listScreenshots",
        ]
        .into_iter()
        .filter(|m| body.contains(&format!("    {m}:")))
        .collect();
        assert_eq!(
            order,
            vec!["deleteScreenshot", "listSaves", "listScreenshots"],
            "{out}"
        );
    }

    /// 单命令组：公共前缀就是整个名字，必须回退一段，否则方法名为空
    #[test]
    fn test_single_command_group() {
        let sigs = vec![sig("windows::collect", "collect_load", vec![], "void")];
        let out = bindings_ts(&[], &sigs, &BTreeMap::new());
        assert!(
            out.contains("    load: () => invoke<void>(\"collect_load\"),\n"),
            "{out}"
        );
    }

    /// 可缺省参数带 `?`
    #[test]
    fn test_optional_param() {
        let sigs = vec![sig(
            "windows::main",
            "main_open",
            vec![("page", "number | null", true)],
            "void",
        )];
        let out = bindings_ts(&[], &sigs, &BTreeMap::new());
        assert!(
            out.contains(
                "    open: (page?: number | null) => invoke<void>(\"main_open\", { page }),\n"
            ),
            "{out}"
        );
    }

    /// 枚举：rename_all 生效，文档注释与 #[default] 不干扰变体名
    #[test]
    fn test_enum_decl() {
        let d = decl(
            "HeadType",
            "#[derive(Serialize)]\n#[serde(rename_all = \"lowercase\")]",
            "\n    /// 默认\n    #[default]\n    Auto,\n    Head,\n",
            true,
        );
        let out = bindings_ts(&[d], &[], &BTreeMap::new());
        assert!(
            out.contains("export type HeadType = \"auto\" | \"head\";\n\n"),
            "{out}"
        );
    }

    /// 无 rename_all 的 struct 键名保持 snake（DirEntry 的现状），camelCase 的转驼峰
    #[test]
    fn test_struct_rename_all() {
        let snake = decl(
            "DirEntry",
            "#[derive(Serialize)]",
            "\n    pub name: String,\n    pub is_dir: bool,\n",
            false,
        );
        let out = bindings_ts(&[snake], &[], &BTreeMap::new());
        assert!(out.contains("  is_dir: boolean,\n"), "{out}");

        let cameled = decl(
            "AccountOAuthStateDto",
            "#[derive(Serialize)]\n#[serde(rename_all = \"camelCase\")]",
            "\n    pub state: String,\n    pub message: Option<String>,\n",
            false,
        );
        let out = bindings_ts(&[cameled], &[], &BTreeMap::new());
        assert!(
            out.contains("  state: string,\n  message: string | null,\n"),
            "{out}"
        );
    }

    /// 只 derive Deserialize 的入参 DTO：`Option` 字段可缺省，非 Option 字段仍必填
    #[test]
    fn test_input_only_dto() {
        let d = decl(
            "SetDto",
            "#[derive(Deserialize)]",
            "\n    pub name: String,\n    pub count: Option<u32>,\n",
            false,
        );
        let out = bindings_ts(&[d], &[], &BTreeMap::new());
        assert!(
            out.contains("  name: string,\n  count?: number | null,\n"),
            "{out}"
        );
    }

    /// 外部 crate 类型走映射表
    #[test]
    fn test_external_type_in_struct() {
        let d = decl(
            "GuiConfigDto",
            "#[derive(Serialize)]\n#[serde(rename_all = \"camelCase\")]",
            "\n    pub lang: Lang,\n",
            false,
        );
        let ext = BTreeMap::from([("Lang".to_string(), "\"zh_cn\" | \"en_us\"".to_string())]);
        let out = bindings_ts(&[d], &[], &ext);
        assert!(out.contains("  lang: \"zh_cn\" | \"en_us\",\n"), "{out}");
    }

    /// listens.ts：事件名转 PascalCase 常量
    #[test]
    fn test_listens_ts() {
        let out = listens_ts(&[
            "add-pack-progress".to_string(),
            "account-change".to_string(),
        ]);
        assert!(
            out.contains("export const AddPackProgress: string = \"add-pack-progress\"\n"),
            "{out}"
        );
        assert!(
            out.contains("export const AccountChange: string = \"account-change\"\n"),
            "{out}"
        );
    }
}
