//! 生成 `$OUT_DIR/invokes_gen.rs`：`listens` 常量 + `tauri_commands!` 注册宏

use crate::ts::screaming;

/// `commands` 是 (命令名, Rust 路径) 对，按 (名, 路径) 排好序
pub(crate) fn invokes_gen(events: &[String], commands: &[(String, String)]) -> String {
    let mut rs = String::from("// @generated by build.rs（扫描 src/ 收集）—— 勿手改\n\n");

    rs.push_str("pub mod listens {\n");
    for name in events {
        rs.push_str(&format!(
            "    pub const {}: &str = \"{}\";\n",
            screaming(name),
            name
        ));
    }
    rs.push_str("}\n\n");

    // 命令注册宏：lib.rs 里 invoke_handler(tauri_commands!())
    rs.push_str("/// generate_handler 注册表（扫描 src/ 生成）\n");
    rs.push_str("#[macro_export]\nmacro_rules! tauri_commands {\n");
    rs.push_str("    () => {\n        tauri::generate_handler![\n");
    for (_, path) in commands {
        rs.push_str(&format!("            {},\n", path));
    }
    rs.push_str("        ]\n    };\n}\n");

    rs
}
