//! IPC 名字源生成器（扫描式，注册表零维护）
//!
//! 扫描 `src/` 源码收集名单：
//! - 命令：`#[tauri::command]` 函数。命令名 = 函数名，Rust 路径 = 文件路径推导的模块路径
//!   （src/windows/account.rs -> windows::account::fn_name）
//! - 事件：`mcml::emit` 标记的函数。事件名 = 函数名去 `emit_` 前缀、`_` -> `-`
//!   （emit_account_change -> account-change）
//!
//! 生成：
//! - `OUT_DIR/invokes_gen.rs`：命令常量（invokes 模块）、事件常量（listens 模块）、
//!   `tauri_commands!` 注册宏
//! - `../../mcml-vue/src/lib/{invokes,listens}.ts`
//!
//! 时序：cargo 编译必先于页面加载（vite 按需编译），TS 生成时机足够；
//! 单独重新生成可跑 `npm run gen`（mcml-gui）。生成的 TS 随仓库提交。

use std::{
    fs,
    path::{Path, PathBuf},
};

/// 递归收集目录下的 .rs 文件
fn walk_rs(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            walk_rs(&path, out);
        } else if path.extension().is_some_and(|e| e == "rs") {
            out.push(path);
        }
    }
}

/// 文件路径 -> Rust 模块路径（src/windows/account.rs -> "windows::account"；
/// mod.rs / lib.rs / main.rs -> 所在目录即模块）
fn module_path(src: &Path, file: &Path) -> String {
    let rel = match file.strip_prefix(src) {
        Ok(rel) => rel,
        Err(_) => return String::new(),
    };
    let mut comps: Vec<String> = rel
        .components()
        .map(|c| c.as_os_str().to_string_lossy().to_string())
        .collect();
    comps.pop();
    let file_name = rel
        .file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_default();
    let stem = file_name.trim_end_matches(".rs");
    // mod.rs / src 根下的 lib.rs、main.rs 不追加自身名，其余文件名即模块名
    let is_special = stem == "mod" || ((stem == "lib" || stem == "main") && comps.is_empty());
    if !is_special {
        comps.push(stem.to_string());
    }
    comps.join("::")
}

/// 找 marker 之后的第一个函数名（跳过中间的文档 / 属性，标准格式下足够可靠）
fn fns_after(text: &str, marker: &str) -> Vec<String> {
    let mut names = Vec::new();
    let mut rest = text;
    while let Some(pos) = rest.find(marker) {
        let after = &rest[pos + marker.len()..];
        if let Some(f) = after.find("fn ") {
            let ident: String = after[f + 3..]
                .chars()
                .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
                .collect();
            if !ident.is_empty() {
                names.push(ident);
            }
        }
        rest = after;
    }
    names
}

/// snake_case / kebab-case -> SCREAMING_SNAKE_CASE（account-change -> ACCOUNT_CHANGE）
fn screaming(name: &str) -> String {
    name.replace('-', "_").to_ascii_uppercase()
}

/// snake_case / kebab-case -> PascalCase，缩写词修正 Oauth -> OAuth
fn pascal(name: &str) -> String {
    name.split(['_', '-'])
        .filter(|s| !s.is_empty())
        .map(|s| {
            let mut chars = s.chars();
            format!(
                "{}{}",
                chars.next().unwrap().to_ascii_uppercase(),
                chars.as_str()
            )
        })
        .collect::<Vec<_>>()
        .join("")
        .replace("Oauth", "OAuth")
}

fn main() {
    tauri_build::build();

    // src 下任何文件变动都触发重新扫描；单独重生成可跑 npm run gen
    println!("cargo:rerun-if-changed=src");
    println!("cargo:rerun-if-changed=build.rs");

    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let src = manifest.join("src");

    let mut files = Vec::new();
    walk_rs(&src, &mut files);
    files.sort();

    // 收集命令（命令名 + Rust 路径）与事件名；排序去重保证输出稳定
    let mut commands: Vec<(String, String)> = Vec::new();
    let mut events: Vec<String> = Vec::new();
    for file in &files {
        let Ok(text) = fs::read_to_string(file) else {
            continue;
        };
        let module = module_path(&src, file);
        for name in fns_after(&text, "#[tauri::command]") {
            let path = if module.is_empty() {
                name.clone()
            } else {
                format!("{module}::{name}")
            };
            commands.push((name, path));
        }
        for name in fns_after(&text, "#[gui_macros::emit]") {
            let event = name
                .strip_prefix("emit_")
                .unwrap_or(&name)
                .replace('_', "-");
            events.push(event);
        }
    }
    commands.sort();
    commands.dedup();
    events.sort();
    events.dedup();

    // ---------- Rust：OUT_DIR/invokes_gen.rs ----------
    let mut rs = String::from("// @generated by build.rs（扫描 src/ 收集）—— 勿手改\n\n");

    rs.push_str("/// 命令名常量（前端对应 mcml-vue/src/lib/invokes.ts）\n");
    rs.push_str("pub mod invokes {\n");
    for (name, _) in &commands {
        rs.push_str(&format!(
            "    pub const {}: &str = \"{}\";\n",
            screaming(name),
            name
        ));
    }
    rs.push_str("}\n\n");
    rs.push_str("pub mod listens {\n");
    for name in &events {
        rs.push_str(&format!(
            "    pub const {}: &str = \"{}\";\n",
            screaming(name),
            name
        ));
    }
    rs.push_str("}\n\n");

    // 命令注册宏：lib.rs 里 invoke_handler(tauri_commands!())
    rs.push_str("/// generate_handler 注册表（扫描 src/ 生成）\n");
    rs.push_str("#[macro_export]\nmacro_rules! tauri_commands {\n");
    rs.push_str("    () => {\n        tauri::generate_handler![\n");
    for (_, path) in &commands {
        rs.push_str(&format!("            {},\n", path));
    }
    rs.push_str("        ]\n    };\n}\n");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    fs::write(out_dir.join("invokes_gen.rs"), rs).expect("写入 invokes_gen.rs 失败");

    // ---------- 前端：mcml-vue/src/lib/{invokes,listens}.ts ----------
    let ts_dir = manifest.join("../../mcml-vue/src/lib");

    let mut ts = String::from(
        "// @generated by mcml-gui/src-tauri/build.rs —— 勿手改，新增命令请给函数加 tauri::command 标记\n\n",
    );
    for (name, _) in &commands {
        ts.push_str(&format!(
            "export const {}: string = \"{}\"\n",
            pascal(name),
            name
        ));
    }
    fs::write(ts_dir.join("invokes.ts"), ts).expect("写入 invokes.ts 失败");

    let mut ts = String::from(
        "// @generated by mcml-gui/src-tauri/build.rs —— 勿手改，新增事件请给函数加 gui_macros::emit 标记\n\n",
    );
    for name in &events {
        ts.push_str(&format!(
            "export const {}: string = \"{}\"\n",
            pascal(name),
            name
        ));
    }
    fs::write(ts_dir.join("listens.ts"), ts).expect("写入 listens.ts 失败");
}
