[package]
name = "mcml-sys"
version = "0.1.0"
edition = "2024"

[dependencies]
mcml-names = { path = "../mcml-names" }
uuid.workspace = true
tokio.workspace = true
clipboard-rs.workspace = true
url.workspace = true

[target.'cfg(linux)'.dependencies]
dbus.workspace = true

[target.'cfg(windows)'.dependencies]
windows.workspace = true
winreg.workspace = true
