// @generated by mcml-gui/src-tauri/build.rs —— 勿手改，新增事件请给函数加 gui_macros::emit 标记

export const AccountChange: string = "account-change"
export const AccountOAuth: string = "account-oauth"
export const AccountOAuthState: string = "account-oauth-state"
export const AddLoaderProgress: string = "add-loader-progress"
export const CloseBlocked: string = "close-blocked"
export const GameExit: string = "game-exit"
export const GameLog: string = "game-log"
export const InstanceChange: string = "instance-change"
export const LaunchError: string = "launch-error"
export const LaunchState: string = "launch-state"
export const LoadDone: string = "load-done"
