[package]
name = "mcml-core"
version = "0.1.0"
edition = "2024"

[dependencies]
mcml-log = { path = "mcml-log" }
mcml-names = { path = "mcml-names" }
mcml-config = { path = "mcml-config" }
mcml-downloader = { path = "mcml-downloader" }
mcml-auth = { path = "mcml-auth" }
mcml-base = { path = "mcml-base" }
mcml-net = { path = "mcml-net" }
crossbeam-queue.workspace = true
tokio.workspace = true
tokio-util.workspace = true
semrs.workspace = true
chrono.workspace = true

[build-dependencies]

[profile.release]

[workspace]
members = [
    "mcml-auth",
    "mcml-base",
    "mcml-config",
    "mcml-downloader",
    "mcml-game",
    "mcml-jvms",
    "mcml-log",
    "mcml-names",
    "mcml-nbt",
    "mcml-net",
    "mcml-skin",
    "mcml-skin-draw",
    "mcml-skin-render",
    "mcml-sys",
]

[workspace.dependencies]
crossbeam-queue = "~0.3.13"
tokio = { version = "~1.53.1", features = [
    "rt",
    "macros",
    "io-util",
    "process",
    "fs",
] }
tokio-util = "~0.7.19"
semrs = "~0.5.2"
reqwest = { version = "~0.13.4", features = ["json", "stream", "form"] }
chrono = { version = "~0.4.45", features = ["serde"] }
serde = { version = "~1.0.229", features = ["derive"] }
serde_json = "~1.0.151"
serde_repr = "~0.1.21"
glow = "~0.18.0"
skia-safe = "~0.99.0"
glam = "~0.33.3"
uuid = { version = "~1.24.0", features = ["v4", "serde"] }
url = "~2.5.8"
md-5 = "~0.11.0"
sha1 = "~0.11.0"
digest = "~0.11.3"
sha2 = "~0.11.0"
base64 = "~0.23.0"
winreg = "~0.56.0"
windows = { version = "~0.62.2", features = [
    "Win32_Foundation",
    "Win32_System_IO",
    "Win32_System_Pipes",
    "Win32_System_Threading",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_SystemInformation",
    "Win32_Storage_FileSystem",
    "Win32_UI_Shell",
    "Win32_System_Com",
] }
zip = { version = "~8.6.0", features = ["chrono"] }
tar = "~0.4.46"
flate2 = "~1.1.9"
sevenz-rust2 = "~0.21.4"
xz2 = { version = "~0.1.7", features = ["static"] }
lz4_flex = "~0.14.0 "
rayon = "~1.12.0"
sys-locale = "~0.3.2"
regex = "~1.13.1"
scraper = "~0.27.0"
itertools = "~0.15.0"
semka = "~2.0.7"
soft-canonicalize = "~0.5.6"
encoding_rs = "~0.8.35"
async-trait = "~0.1.91"
encoding_rs_io = "~0.1.7"
notify = "~8.2.0"
toml = "~1.1.4"
if-addrs = "~0.15.0"
socket2 = "~0.6.5"
image = "~0.25.10"
ico = "~0.5.0"
clipboard-rs = "~0.3.5"
webbrowser = "~1.2.4"
opener = { version = "~0.8.5", features = ["reveal"] }