// @generated by mml-gui/src-tauri/build.rs —— 勿手改
//
// 命令的类型化包装 + 跨 IPC 类型的 TS 定义，都由 Rust 侧源码扫描生成。

import { invoke } from "@tauri-apps/api/core";

/** 命令，按来源 .rs 模块分组（参数顺序与 Rust 一致，Tauri 注入的 AppHandle/WebviewWindow 已剔除）*/
export const commands = {
  windows: {
    closeWindow: (kind: string) => invoke<void>("window_close_window", { kind }),
    getGuiConfig: () => invoke<GuiConfigDto>("window_get_gui_config"),
    getWindowSizes: () => invoke<WindowSizeDto[]>("window_get_window_sizes"),
    isMaximized: () => invoke<boolean>("window_is_maximized"),
    minimize: () => invoke<void>("window_minimize"),
    openWindow: (kind: string) => invoke<void>("window_open_window", { kind }),
    saveGuiConfig: (config: GuiConfigDto) => invoke<void>("window_save_gui_config", { config }),
    setTitle: (title: string) => invoke<void>("window_set_title", { title }),
    startDragging: () => invoke<void>("window_start_dragging"),
    toggleMaximize: () => invoke<boolean>("window_toggle_maximize"),
  },
  account: {
    addAccount: (name: string, accountType: string, server: string | null, password: string | null) => invoke<AccountStoreDto>("account_add_account", { name, accountType, server, password }),
    cancelOAuth: () => invoke<void>("account_cancel_oauth"),
    editOffline: (uuid: string, newName: string, newUuid: string) => invoke<void>("account_edit_offline", { uuid, newName, newUuid }),
    getAccounts: () => invoke<AccountStoreViewDto>("account_get_accounts"),
    openBrowser: (url: string) => invoke<void>("account_open_browser", { url }),
    refreshAccountToken: (uuid: string) => invoke<boolean>("account_refresh_account_token", { uuid }),
    removeAccount: (uuid: string) => invoke<boolean>("account_remove_account", { uuid }),
    setCurrentAccount: (uuid: string) => invoke<boolean>("account_set_current_account", { uuid }),
  },
  add: {
    answerNameConflict: (id: number, answer: boolean) => invoke<void>("add_answer_name_conflict", { id, answer }),
    cancel: () => invoke<boolean>("add_cancel"),
    createNew: (name: string, version: string, loader: string, loaderVersion: string | null, group: string | null) => invoke<string>("add_create_new", { name, version, loader, loaderVersion, group }),
    detectArchive: (path: string) => invoke<DetectedPackDto>("add_detect_archive", { path }),
    getLoaderVersions: (loader: string, mc: string) => invoke<string[]>("add_get_loader_versions", { loader, mc }),
    getLoaders: () => invoke<string[]>("add_get_loaders"),
    getPackTypes: () => invoke<string[]>("add_get_pack_types"),
    getSupportLoaders: (mc: string) => invoke<string[]>("add_get_support_loaders", { mc }),
    getVersionTypes: () => invoke<string[]>("add_get_version_types"),
    importArchive: (path: string, packType: string, name: string | null, group: string | null, unselect: string[] | null) => invoke<string>("add_import_archive", { path, packType, name, group, unselect }),
    importFolder: (path: string, name: string | null, group: string | null) => invoke<string>("add_import_folder", { path, name, group }),
    importUrl: (url: string, name: string | null, group: string | null) => invoke<string>("add_import_url", { url, name, group }),
    listArchive: (path: string) => invoke<string[]>("add_list_archive", { path }),
    listDir: (path: string) => invoke<DirEntry[]>("add_list_dir", { path }),
    setCloseGuard: (enabled: boolean) => invoke<void>("add_set_close_guard", { enabled }),
  },
  addModpack: {
    cancel: (pid: string, fid: string) => invoke<void>("add_modpack_cancel", { pid, fid }),
    clearDone: () => invoke<void>("add_modpack_clear_done"),
    detail: (source: string, pid: string) => invoke<ProjectDetailDto>("add_modpack_detail", { source, pid }),
    file: (source: string, pid: string, page: number, version: string | null) => invoke<FileListDto>("add_modpack_file", { source, pid, page, version }),
    install: (source: string, projectId: string, fileId: string, group: string | null) => invoke<void>("add_modpack_install", { source, projectId, fileId, group }),
    list: (source: string, page: number, sort: string, category: string | null, filter: string | null, version: string | null) => invoke<ProjectDto>("add_modpack_list", { source, page, sort, category, filter, version }),
    status: () => invoke<ModPackStatusDto>("add_modpack_status"),
  },
  addResource: {
    categories: (source: string, fileType: string) => invoke<Record<string, string>>("add_resource_categories", { source, fileType }),
    download: (game: string, source: string, pid: string, fid: string, fileType: string, world: string | null) => invoke<void>("add_resource_download", { game, source, pid, fid, fileType, world }),
    file: (game: string, source: string, pid: string, fileType: string, page: number, version: string | null, loader: string | null) => invoke<FileListDto>("add_resource_file", { game, source, pid, fileType, page, version, loader }),
    gameVersions: (source: string) => invoke<string[]>("add_resource_game_versions", { source }),
    list: (game: string, source: string, fileType: string, page: number, sort: string, category: string | null, filter: string | null, version: string | null, loader: string | null) => invoke<ProjectDto>("add_resource_list", { game, source, fileType, page, sort, category, filter, version, loader }),
    saves: (game: string) => invoke<ResourceSaveDto[]>("add_resource_saves", { game }),
    sortType: (source: string) => invoke<string[]>("add_resource_sort_type", { source }),
    sourceType: () => invoke<string[]>("add_resource_source_type"),
    status: () => invoke<ResourceStatusDto>("add_resource_status"),
  },
  block: {
    list: (lang: string) => invoke<BlockItemDto[]>("block_list", { lang }),
    renderStart: (force: boolean) => invoke<boolean>("block_render_start", { force }),
    setIcon: (uuid: string, id: string) => invoke<boolean>("block_set_icon", { uuid, id }),
    skinAdd: (input: string) => invoke<string>("block_skin_add", { input }),
    skinRemove: (name: string) => invoke<void>("block_skin_remove", { name }),
    status: () => invoke<BlockStatusDto>("block_status"),
  },
  collect: {
    addGroup: (name: string) => invoke<void>("collect_add_group", { name }),
    clear: (group: string | null) => invoke<void>("collect_clear", { group }),
    getData: () => invoke<CollectDataDto>("collect_get_data"),
    removeGroup: (name: string) => invoke<void>("collect_remove_group", { name }),
    removeItems: (uuids: string[], group: string | null) => invoke<void>("collect_remove_items", { uuids, group }),
    setGroupItems: (group: string, uuids: string[]) => invoke<void>("collect_set_group_items", { group, uuids }),
    star: (source: string, fileType: string, pid: string, name: string, icon: string | null, url: string, star: boolean) => invoke<void>("collect_star", { source, fileType, pid, name, icon, url, star }),
  },
  download: {
    cancelAll: () => invoke<number>("download_cancel_all"),
    getStatus: () => invoke<DownloadStatusDto>("download_get_status"),
    pauseAll: () => invoke<number>("download_pause_all"),
    resumeAll: () => invoke<number>("download_resume_all"),
  },
  main: {
    addGroup: (name: string) => invoke<boolean>("main_add_group", { name }),
    addJava: (name: string, path: string) => invoke<boolean>("main_add_java", { name, path }),
    createInstance: (name: string, version: string, loader: string | null, loaderVersion: string | null, group: string | null, modpackType: string | null, source: string | null) => invoke<InstanceInfoDto>("main_create_instance", { name, version, loader, loaderVersion, group, modpackType, source }),
    deleteInstance: (uuid: string) => invoke<boolean>("main_delete_instance", { uuid }),
    getGameLog: (uuid: string) => invoke<LogLine[]>("main_get_game_log", { uuid }),
    getGroups: () => invoke<string[]>("main_get_groups"),
    getInstanceArgs: (uuid: string) => invoke<InstanceArgsDto>("main_get_instance_args", { uuid }),
    getInstanceLangs: (uuid: string) => invoke<string[]>("main_get_instance_langs", { uuid }),
    getInstances: () => invoke<InstanceInfoDto[]>("main_get_instances"),
    getJavaList: () => invoke<JavaInfoDto[]>("main_get_java_list"),
    getNews: (page: number | null) => invoke<NewsItem[]>("main_get_news", { page }),
    getRunning: () => invoke<string[]>("main_get_running"),
    getVersions: () => invoke<VersionInfoDto[]>("main_get_versions"),
    imageBaseUrl: () => invoke<string>("main_image_base_url"),
    launchGame: (uuid: string) => invoke<void>("main_launch_game", { uuid }),
    loadState: () => invoke<LoadState>("main_load_state"),
    moveGroup: (name: string, index: number) => invoke<boolean>("main_move_group", { name, index }),
    moveInstance: (uuid: string, group: string | null, index: number) => invoke<boolean>("main_move_instance", { uuid, group, index }),
    openUrl: (url: string) => invoke<void>("main_open_url", { url }),
    refreshVersions: () => invoke<VersionInfoDto[]>("main_refresh_versions"),
    removeGroup: (name: string) => invoke<boolean>("main_remove_group", { name }),
    removeJava: (name: string) => invoke<void>("main_remove_java", { name }),
    renameInstance: (uuid: string, name: string) => invoke<boolean>("main_rename_instance", { uuid, name }),
    scanJava: () => invoke<JavaInfoDto[]>("main_scan_java"),
    stopGame: (uuid: string) => invoke<void>("main_stop_game", { uuid }),
    updateInstance: (uuid: string, patch: InstancePatch) => invoke<boolean>("main_update_instance", { uuid, patch }),
    updateInstanceArgs: (uuid: string, args: InstanceArgsDto) => invoke<boolean>("main_update_instance_args", { uuid, args }),
  },
  resource: {
    backupSave: (uuid: string, dir: string) => invoke<string>("resource_backup_save", { uuid, dir }),
    clearScreenshots: (uuid: string) => invoke<void>("resource_clear_screenshots", { uuid }),
    datapackDelete: (uuid: string, dir: string, name: string) => invoke<void>("resource_datapack_delete", { uuid, dir, name }),
    datapackToggle: (uuid: string, dir: string, name: string) => invoke<void>("resource_datapack_toggle", { uuid, dir, name }),
    deleteMod: (uuid: string, modUuid: string) => invoke<void>("resource_delete_mod", { uuid, modUuid }),
    deleteResourcepack: (uuid: string, file: string) => invoke<void>("resource_delete_resourcepack", { uuid, file }),
    deleteSave: (uuid: string, dir: string) => invoke<void>("resource_delete_save", { uuid, dir }),
    deleteSchematic: (uuid: string, file: string) => invoke<void>("resource_delete_schematic", { uuid, file }),
    deleteScreenshot: (uuid: string, name: string) => invoke<void>("resource_delete_screenshot", { uuid, name }),
    deleteShaderpack: (uuid: string, file: string) => invoke<void>("resource_delete_shaderpack", { uuid, file }),
    listDatapacks: (uuid: string, dir: string) => invoke<DataPackItemDto[]>("resource_list_datapacks", { uuid, dir }),
    listMods: (uuid: string) => invoke<ModItemDto[]>("resource_list_mods", { uuid }),
    listResourcepacks: (uuid: string) => invoke<PackItemDto[]>("resource_list_resourcepacks", { uuid }),
    listSaves: (uuid: string) => invoke<SaveItemDto[]>("resource_list_saves", { uuid }),
    listSchematics: (uuid: string) => invoke<SchematicItemDto[]>("resource_list_schematics", { uuid }),
    listScreenshots: (uuid: string) => invoke<ScreenshotItemDto[]>("resource_list_screenshots", { uuid }),
    listServers: (uuid: string) => invoke<ServerItemDto[]>("resource_list_servers", { uuid }),
    listShaderpacks: (uuid: string) => invoke<ShaderItemDto[]>("resource_list_shaderpacks", { uuid }),
    modDisable: (uuid: string, modUuid: string) => invoke<void>("resource_mod_disable", { uuid, modUuid }),
    modEnable: (uuid: string, modUuid: string) => invoke<void>("resource_mod_enable", { uuid, modUuid }),
    openFolder: (uuid: string, kind: string, name: string | null, parent: string | null) => invoke<void>("resource_open_folder", { uuid, kind, name, parent }),
    serverAdd: (uuid: string, name: string, ip: string) => invoke<void>("resource_server_add", { uuid, name, ip }),
    serverDelete: (uuid: string, name: string, ip: string) => invoke<void>("resource_server_delete", { uuid, name, ip }),
    serverUpdate: (uuid: string, name: string, ip: string, newName: string, newIp: string, acceptTextures: boolean) => invoke<void>("resource_server_update", { uuid, name, ip, newName, newIp, acceptTextures }),
    shaderSet: (uuid: string, file: string | null) => invoke<void>("resource_shader_set", { uuid, file }),
  },
  settings: {
    addJava: (path: string) => invoke<JavaInfoDto>("settings_add_java", { path }),
    clearBg: () => invoke<void>("settings_clear_bg"),
    getBg: () => invoke<BgInfoDto | null>("settings_get_bg"),
    getLaunch: () => invoke<LaunchSettingDto>("settings_get_launch"),
    getNetwork: () => invoke<NetworkSettingDto>("settings_get_network"),
    getSystemFonts: () => invoke<string[]>("settings_get_system_fonts"),
    removeJava: (name: string) => invoke<JavaInfoDto[]>("settings_remove_java", { name }),
    resizeBg: (percent: number) => invoke<string>("settings_resize_bg", { percent }),
    saveLaunch: (minMemory: number, maxMemory: number, jvmArgs: string, gameArgs: string) => invoke<void>("settings_save_launch", { minMemory, maxMemory, jvmArgs, gameArgs }),
    saveNetwork: (dto: NetworkSettingDto) => invoke<void>("settings_save_network", { dto }),
    scanJava: () => invoke<JavaInfoDto[]>("settings_scan_java"),
    setBg: (source: string, percent: number) => invoke<string>("settings_set_bg", { source, percent }),
  },
};

/** 类型 */
export type AccountStoreViewDto = {
  accounts: AccountStoreDto[],
  currentUuid: string | null,
};

export type AccountStoreDto = {
  userName: string,
  uuid: string,
  authType: string,
  loginTime: string,
  avatarColor: string,
  skin: string,
  tokenStatus: string,
  avatar: string | null,
  server: string | null,
  ext1: string | null,
  ext2: string | null,
  canRefresh: boolean,
  canRelogin: boolean,
  canEdit: boolean,
};

export type AccountOAuthDto = {
  code: string,
  url: string,
};

export type AccountOAuthStateDto = {
  state: string,
  message: string | null,
};

export type DirEntry = {
  name: string,
  isDir: boolean,
};

export type LoaderProgressDto = {
  step: number,
  total: number,
};

export type NameConflictDto = {
  id: number,
  kind: string,
  name: string,
};

export type DetectedPackDto = {
  packType: string,
  name: string,
};

export type ModpackItemDto = {
  id: string,
  name: string,
  desc: string,
  icon: string,
  author: string,
  downloads: number,
};

export type PackProgressDto = {
  state: string,
  now: number,
  total: number,
  subText: string | null,
  subNow: number,
  subTotal: number,
};

export type ModPackTaskDto = {
  uuid: string,
  source: string,
  pid: string,
  fid: string,
  name: string,
  state: string,
  now: number,
  total: number,
  subText: string | null,
  subNow: number,
  subTotal: number,
  done: boolean,
  failed: boolean,
  cancelled: boolean,
  error: string | null,
  instanceUuid: string | null,
};

export type ModPackStatusDto = {
  windowOpen: boolean,
  tasks: ModPackTaskDto[],
};

export type FileListDto = {
  list: FileListItemDto[],
  count: number,
  name: string,
  maxPage: number,
};

export type FileListItemDto = {
  name: string,
  download: number,
  size: number,
  time: string,
  isDownload: boolean,
  downloadNow: boolean,
  source: SourceTypeDto,
};

export type SourceTypeDto = {
  fileType: string,
  source: string,
  pid: string,
  fid: string,
};

export type ProjectDto = {
  items: ProjectItemDto[],
  count: number,
};

export type ProjectItemDto = {
  name: string,
  summary: string,
  image: string | null,
  authors: PicDto[],
  tag: TagDto[],
  screenshots: DecPicDto[],
  downloadCount: number,
  date: string,
  download: boolean,
  canStar: boolean,
  isStar: boolean,
  downloadNow: boolean,
  url: string,
  mcmod: McmodDto | null,
  source: SourceTypeDto,
};

export type ProjectDetailDto = {
  summary: string,
  body: string | null,
  authors: PicDto[],
  tag: TagDto[],
  screenshots: DecPicDto[],
};

export type McmodDto = {
  mcmodId: string,
  mcmodName: string,
};

export type PicDto = {
  name: string,
  logo: string | null,
};

export type TagDto = {
  name: string,
  logo: string | null,
  svg: string | null,
};

export type DecPicDto = {
  name: string,
  logo: string,
  description: string,
};

export type ResourceSaveDto = {
  name: string,
  dir: string,
};

export type ResourceTaskDto = {
  pid: string,
  fid: string,
  name: string,
  progress: number,
  done: boolean,
  failed: boolean,
};

export type ResourceStatusDto = {
  windowOpen: boolean,
  tasks: ResourceTaskDto[],
};

export type EnvVarLineDto = {
  key: string,
  value: string,
};

export type InstanceArgsDto = {
  memory: number,
  minMemory: number,
  fullscreen: boolean,
  width: number,
  height: number,
  javaName: string,
  javaPath: string,
  gc: string,
  gcCustom: string,
  mainClass: string,
  jvmArgs: string[],
  gameArgs: string[],
  classPath: string[],
  envVars: EnvVarLineDto[],
  lang: string,
  logEncoding: string,
  preEnabled: boolean,
  preCmd: string,
  postEnabled: boolean,
  postCmd: string,
  proxyIp: string,
  proxyPort: number,
  proxyUser: string,
  proxyPass: string,
  serverIp: string,
  serverPort: number,
  joinServer: boolean,
};

export type CollectItemDto = {
  uuid: string,
  name: string,
  source: string,
  fileType: string,
  pid: string,
  icon: string | null,
  url: string,
};

export type CollectDataDto = {
  items: CollectItemDto[],
  groups: Record<string, string[]>,
};

export type DownloadTaskEvent = {
  type: string,
  id: number,
  progress: number,
};

export type DownloadItemEvent = {
  thread: number,
  name: string,
  state: string,
};

export type DownloadTaskDto = {
  id: number,
  total: number,
  completed: number,
  failed: number,
  allBytes: number,
  nowBytes: number,
  elapsedMs: number,
  paused: boolean,
};

export type DownloadThreadDto = {
  thread: number,
  name: string,
  state: string,
  progress: number,
  nowBytes: number,
  allBytes: number,
  speed: number,
};

export type DownloadStatusDto = {
  tasks: DownloadTaskDto[],
  threads: DownloadThreadDto[],
  speed: number,
  paused: boolean,
};

export type HeadConfigDto = {
  headType: HeadType,
  x: number,
  y: number,
};

export type MainWindowConfigDto = {
  sidebarSide: SidebarSide,
  sidebarCollapsed: boolean,
  viewMode: ViewMode,
  selectedInstance: string,
};

export type CollectConfigDto = {
  modpack: boolean,
  showMod: boolean,
  resourcePack: boolean,
  shaderpack: boolean,
};

export type GuiConfigDto = {
  theme: Theme,
  locale: "zh_cn" | "en_us",
  windowMode: WindowMode,
  mainWindow: MainWindowConfigDto,
  head: HeadConfigDto,
  collect: CollectConfigDto,
  font: string,
  skinDisplay: SkinDisplay,
  bgSource: string,
  bgOpacity: number,
  bgBlur: number,
  bgNativeSize: number,
};

export type InstanceInfoDto = {
  uuid: string,
  name: string,
  group: string | null,
  version: string,
  versionType: string | null,
  loader: string,
  loaderVersion: string | null,
  dir: string,
  running: boolean,
  modpackType: string | null,
  pid: string | null,
  fid: string | null,
  serverUrl: string | null,
  lang: string | null,
  logEncoding: string | null,
  source: string | null,
};

export type JavaInfoDto = {
  name: string,
  path: string,
  version: string,
  major: number,
  javaType: string,
  arch: string,
};

export type LoadState = {
  ok: boolean,
  error: string | null,
};

export type NewsItem = {
  id: number,
  title: string,
  date: string,
  tag: string,
  image: string,
  url: string,
};

export type LogEvent = {
  uuid: string,
  time: string,
  text: string,
  thread: string,
  level: string,
  category: string,
  clear: boolean,
};

export type LogLine = {
  time: string,
  text: string,
  thread: string,
  level: string,
  category: string,
};

export type StateEvent = {
  uuid: string,
  state: string,
  progress: number | null,
};

export type ExitEvent = {
  uuid: string,
  code: number,
};

export type ErrorEvent = {
  uuid: string | null,
  message: string,
};

export type InstanceChangeEvent = {
  type: string,
};

export type InstancePatch = {
  group?: string | null,
  name?: string | null,
  version?: string | null,
  versionType?: string | null,
  loader?: string | null,
  loaderVersion?: string | null,
  modpackType?: string | null,
  pid?: string | null,
  fid?: string | null,
  serverUrl?: string | null,
  lang?: string | null,
  logEncoding?: string | null,
};

export type BlockItemDto = {
  id: string,
  name: string,
  cat: string,
  image: string,
};

export type BlockStatusDto = {
  rendered: boolean,
  optIn: boolean,
  version: string,
  running: boolean,
  now: number,
  total: number,
  text: string | null,
  error: string | null,
};

export type ModItemDto = {
  uuid: string,
  file: string,
  disable: boolean,
  fail: boolean,
  core: boolean,
  modId: string,
  name: string,
  version: string,
  author: string,
  description: string,
  icon: string,
};

export type PackItemDto = {
  file: string,
  description: string,
  packFormat: number,
  minFormat: number,
  maxFormat: number,
  fail: boolean,
  icon: string,
};

export type SaveItemDto = {
  dir: string,
  levelName: string,
  lastPlayed: number,
  gameType: number,
  hardCore: boolean,
  difficulty: number,
  broken: boolean,
  icon: string,
};

export type ScreenshotItemDto = {
  name: string,
};

export type ServerItemDto = {
  name: string,
  ip: string,
  acceptTextures: boolean,
  icon: string,
};

export type ShaderItemDto = {
  file: string,
  name: string,
  comment: string,
  selected: boolean,
};

export type SchematicItemDto = {
  file: string,
  name: string,
  author: string,
  description: string,
  typeName: string,
  width: number,
  height: number,
  length: number,
  blockCount: number,
  blockTypes: number,
  fail: boolean,
};

export type DataPackItemDto = {
  name: string,
  file: string,
  description: string,
  packFormat: number,
  enable: boolean | null,
};

export type NetworkSettingDto = {
  source: string,
  downloadThread: number,
  proxyIp: string,
  proxyPort: number,
  proxyUser: string,
  proxyPassword: string,
  workProxy: string,
  workProxyType: string,
  loginProxy: string,
  loginProxyType: string,
  checkFile: boolean,
  autoDownload: boolean,
  dns: DnsSettingDto,
  check: GameCheckSettingDto,
};

export type DnsSettingDto = {
  enable: boolean,
  https: string[],
  httpProxy: boolean,
};

export type GameCheckSettingDto = {
  core: boolean,
  lib: boolean,
  assets: boolean,
  gameMod: boolean,
  coreSha1: boolean,
  libSha1: boolean,
  assetsSha1: boolean,
  modSha1: boolean,
};

export type LaunchSettingDto = {
  javaList: JavaInfoDto[],
  minMemory: number,
  maxMemory: number,
  jvmArgs: string,
  gameArgs: string,
};

export type BgInfoDto = {
  source: string,
  dataUrl: string,
  opacity: number,
  blur: number,
  nativeSize: number,
};

export type VersionInfoDto = {
  id: string,
  versionType: string,
};

export type WindowSizeDto = {
  kind: string,
  width: number,
  height: number,
};

export type Theme = "System" | "Light" | "Dark";

export type WindowMode = "Multi" | "Single";

export type SidebarSide = "Left" | "Right";

export type ViewMode = "list" | "group" | "grid";

export type SkinDisplay = "Skin2DA" | "Skin2DB" | "Skin3D";

export type HeadType = "Head2DA" | "Head3DA" | "Head3DB" | "Head3DC" | "Head2DB";

