//! 生成前端 TS 文本：`listens.ts`（事件名常量）与 `bindings.ts`（类型 + 命令包装）

use std::collections::BTreeMap;

use crate::{
    Decl, Sig,
    scan::{rename_all_of, split_top_level},
    ts::{camel, pascal, ts_field},
};

/// `mcml-vue/src/lib/listens.ts`
pub(crate) fn listens_ts(events: &[String]) -> String {
    let mut ts = String::from(
        "// @generated by mcml-gui/src-tauri/build.rs —— 勿手改，新增事件请给函数加 gui_macros::emit 标记\n\n",
    );
    for name in events {
        ts.push_str(&format!(
            "export const {}: string = \"{}\"\n",
            pascal(name),
            name
        ));
    }
    ts
}

/// `mcml-vue/src/lib/bindings.ts`
pub(crate) fn bindings_ts(
    decls: &[Decl],
    sigs: &[Sig],
    ext: &BTreeMap<String, String>,
) -> String {
    let mut b = String::from(
        "// @generated by mcml-gui/src-tauri/build.rs —— 勿手改\n\
         //\n\
         // 命令的类型化包装 + 跨 IPC 类型的 TS 定义，都由 Rust 侧源码扫描生成。\n\n\
         import { invoke } from \"@tauri-apps/api/core\";\n\n",
    );

    append_commands(&mut b, sigs);
    append_types(&mut b, decls, ext);

    b
}

// 命令表：按来源 .rs 模块分组（AGENTS §4 下，命令名 = 窗口名_方法名，
// 所以同一文件里的命令共享同一个前段；把它剥掉，组内只剩方法名）
fn append_commands(b: &mut String, sigs: &[Sig]) {
    b.push_str("/** 命令，按来源 .rs 模块分组（参数顺序与 Rust 一致，Tauri 注入的 AppHandle/WebviewWindow 已剔除）*/\n");
    b.push_str("export const commands = {\n");

    let mut i = 0usize;
    while i < sigs.len() {
        let module = sigs[i].module.clone();
        let start = i;
        while i < sigs.len() && sigs[i].module == module {
            i += 1;
        }
        let group = &sigs[start..i];

        // 组键取模块最后一段（即 .rs 文件名），如 windows::main -> main
        let group_key = camel(module.rsplit("::").next().unwrap_or(&module));

        // 组内命令名的公共前段，按 `_` 分段取最长公共前缀
        // （`add.rs` -> `add`；`add_modpack.rs` -> `add_modpack`；`window_manager.rs` -> `window`）
        let segs = |n: &str| n.split('_').map(|s| s.to_string()).collect::<Vec<_>>();
        let mut common = segs(&group[0].name);
        for s in group {
            let other = segs(&s.name);
            let mut k = 0;
            while k < common.len() && k < other.len() && common[k] == other[k] {
                k += 1;
            }
            common.truncate(k);
        }
        // 公共前缀不能吃掉整个名字，否则方法名会空（单命令组会走到这里）
        let mut strip_len = common.len();
        if strip_len > 0 && group.iter().any(|s| segs(&s.name).len() == strip_len) {
            strip_len -= 1;
        }
        let strip = if strip_len == 0 {
            None
        } else {
            Some(common[..strip_len].join("_") + "_")
        };

        b.push_str(&format!("  {group_key}: {{\n"));
        for s in group {
            let name = &s.name;
            let ret = &s.ret;
            let method = camel(match &strip {
                Some(prefix) => s.name.strip_prefix(prefix).unwrap_or(&s.name),
                None => s.name.as_str(),
            });
            let list = s
                .params
                .iter()
                .map(|(n, t, opt)| format!("{n}{}: {t}", if *opt { "?" } else { "" }))
                .collect::<Vec<_>>()
                .join(", ");
            let arg = if s.params.is_empty() {
                String::new()
            } else {
                let obj = s
                    .params
                    .iter()
                    .map(|(n, _, _)| n.clone())
                    .collect::<Vec<_>>()
                    .join(", ");
                format!(", {{ {obj} }}")
            };
            b.push_str(&format!(
                "    {method}: ({list}) => invoke<{ret}>(\"{name}\"{arg}),\n"
            ));
        }
        b.push_str("  },\n");
    }
    b.push_str("};\n\n");
}

fn append_types(b: &mut String, decls: &[Decl], ext: &BTreeMap<String, String>) {
    b.push_str("/** 类型 */\n");
    for d in decls {
        let rename_all = rename_all_of(&d.attrs);
        if d.is_enum {
            let variants: Vec<String> = split_top_level(&d.body)
                .into_iter()
                .filter_map(|v| {
                    // 跳过变体前置的文档注释与属性（如 `#[default]`），再取标识符
                    let line = v
                        .lines()
                        .map(|l| l.trim())
                        .find(|l| !l.is_empty() && !l.starts_with("//") && !l.starts_with("#["))?;
                    let name: String = line
                        .chars()
                        .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
                        .collect();
                    if name.is_empty() {
                        return None;
                    }
                    Some(match rename_all.as_deref() {
                        Some("lowercase") => name.to_ascii_lowercase(),
                        Some("camelCase") => camel(&name),
                        _ => name,
                    })
                })
                .collect();
            b.push_str(&format!(
                "export type {} = {};\n\n",
                d.name,
                variants
                    .iter()
                    .map(|v| format!("\"{v}\""))
                    .collect::<Vec<_>>()
                    .join(" | ")
            ));
            continue;
        }

        // 只 derive Deserialize = 前端传给后端的入参 DTO（字段可缺省，见 ts_field）
        let input_only = !d.attrs.contains("Serialize");
        b.push_str(&format!("export type {} = {{\n", d.name));
        for line in d.body.lines() {
            let line = line.trim();
            if line.starts_with("//") || line.starts_with("#[") || line.is_empty() {
                continue;
            }
            let Some((raw_name, raw_ty)) = line.split_once(':') else {
                continue;
            };
            let raw_name = raw_name.trim().trim_start_matches("pub ").trim();
            if raw_name.is_empty() || raw_name.starts_with('/') {
                continue;
            }
            let raw_name = raw_name.trim_start_matches("r#");
            let raw_ty = raw_ty.trim().trim_end_matches(',').trim();
            let ts_name = match rename_all.as_deref() {
                Some("camelCase") => camel(raw_name),
                Some("lowercase") => raw_name.to_ascii_lowercase(),
                _ => raw_name.to_string(),
            };
            let (ts, opt) = ts_field(raw_ty, input_only, ext);
            b.push_str(&format!("  {ts_name}{}: {ts},\n", if opt { "?" } else { "" }));
        }
        b.push_str("};\n\n");
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{Decl, Sig};

    fn sig(module: &str, name: &str, params: Vec<(&str, &str, bool)>, ret: &str) -> Sig {
        Sig {
            module: module.into(),
            name: name.into(),
            params: params
                .into_iter()
                .map(|(n, t, o)| (n.into(), t.into(), o))
                .collect(),
            ret: ret.into(),
        }
    }

    fn decl(name: &str, attrs: &str, body: &str, is_enum: bool) -> Decl {
        Decl {
            name: name.into(),
            attrs: attrs.into(),
            body: body.into(),
            is_enum,
        }
    }

    /// 组键取模块最后一段，方法名剥掉组内公共前段
    #[test]
    fn test_group_and_prefix_strip() {
        let sigs = vec![
            sig("windows::add_modpack", "add_modpack_search", vec![("source", "string", false)], "ModpackSearchDto"),
            sig("windows::add_modpack", "add_modpack_start", vec![], "void"),
        ];
        let out = bindings_ts(&[], &sigs, &BTreeMap::new());
        assert!(out.contains("  addModpack: {\n"), "{out}");
        assert!(out.contains("    search: (source: string) => invoke<ModpackSearchDto>(\"add_modpack_search\", { source }),\n"), "{out}");
        // 无参数的命令不带对象实参
        assert!(out.contains("    start: () => invoke<void>(\"add_modpack_start\"),\n"), "{out}");
    }

    /// 单命令组：公共前缀就是整个名字，必须回退一段，否则方法名为空
    #[test]
    fn test_single_command_group() {
        let sigs = vec![sig("windows::collect", "collect_load", vec![], "void")];
        let out = bindings_ts(&[], &sigs, &BTreeMap::new());
        assert!(out.contains("    load: () => invoke<void>(\"collect_load\"),\n"), "{out}");
    }

    /// 可缺省参数带 `?`
    #[test]
    fn test_optional_param() {
        let sigs = vec![sig("windows::main", "main_open", vec![("page", "number | null", true)], "void")];
        let out = bindings_ts(&[], &sigs, &BTreeMap::new());
        assert!(out.contains("    open: (page?: number | null) => invoke<void>(\"main_open\", { page }),\n"), "{out}");
    }

    /// 枚举：rename_all 生效，文档注释与 #[default] 不干扰变体名
    #[test]
    fn test_enum_decl() {
        let d = decl(
            "HeadType",
            "#[derive(Serialize)]\n#[serde(rename_all = \"lowercase\")]",
            "\n    /// 默认\n    #[default]\n    Auto,\n    Head,\n",
            true,
        );
        let out = bindings_ts(&[d], &[], &BTreeMap::new());
        assert!(out.contains("export type HeadType = \"auto\" | \"head\";\n\n"), "{out}");
    }

    /// 无 rename_all 的 struct 键名保持 snake（DirEntry 的现状），camelCase 的转驼峰
    #[test]
    fn test_struct_rename_all() {
        let snake = decl("DirEntry", "#[derive(Serialize)]", "\n    pub name: String,\n    pub is_dir: bool,\n", false);
        let out = bindings_ts(&[snake], &[], &BTreeMap::new());
        assert!(out.contains("  is_dir: boolean,\n"), "{out}");

        let cameled = decl("AccountOAuthStateDto", "#[derive(Serialize)]\n#[serde(rename_all = \"camelCase\")]", "\n    pub state: String,\n    pub message: Option<String>,\n", false);
        let out = bindings_ts(&[cameled], &[], &BTreeMap::new());
        assert!(out.contains("  state: string,\n  message: string | null,\n"), "{out}");
    }

    /// 只 derive Deserialize 的入参 DTO：`Option` 字段可缺省，非 Option 字段仍必填
    #[test]
    fn test_input_only_dto() {
        let d = decl("SetDto", "#[derive(Deserialize)]", "\n    pub name: String,\n    pub count: Option<u32>,\n", false);
        let out = bindings_ts(&[d], &[], &BTreeMap::new());
        assert!(out.contains("  name: string,\n  count?: number | null,\n"), "{out}");
    }

    /// 外部 crate 类型走映射表
    #[test]
    fn test_external_type_in_struct() {
        let d = decl("GuiConfigDto", "#[derive(Serialize)]\n#[serde(rename_all = \"camelCase\")]", "\n    pub lang: Lang,\n", false);
        let ext = BTreeMap::from([("Lang".to_string(), "\"zh_cn\" | \"en_us\"".to_string())]);
        let out = bindings_ts(&[d], &[], &ext);
        assert!(out.contains("  lang: \"zh_cn\" | \"en_us\",\n"), "{out}");
    }

    /// listens.ts：事件名转 PascalCase 常量
    #[test]
    fn test_listens_ts() {
        let out = listens_ts(&["add-pack-progress".to_string(), "account-change".to_string()]);
        assert!(out.contains("export const AddPackProgress: string = \"add-pack-progress\"\n"), "{out}");
        assert!(out.contains("export const AccountChange: string = \"account-change\"\n"), "{out}");
    }
}
