[package]
name = "mml-auth"
version = "0.1.0"
edition = "2024"

[dependencies]
mml-log = { path = "../mml-log" }
mml-config = { path = "../mml-config" }
mml-net = { path = "../mml-net" }
mml-names = { path = "../mml-names" }
mml-base = { path = "../mml-base" }
tokio.workspace = true
tokio-util.workspace = true
crossbeam-queue.workspace = true
reqwest.workspace = true
serde.workspace = true
chrono.workspace = true
serde_json.workspace = true
serde_repr.workspace = true
